app = "levelbyte"
primary_region = "gru"

[build]
  dockerfile = "./dockerfile"

[env]
  ASPNETCORE_URLS = "http://+:8080"

[http_service]
  internal_port = 8080
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 0
  force_https = true
